// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg8afJNgbJqDmnQTtuzZV7-pdKjePgCQg',
    appId: '1:235265179206:web:d588d323f67040d2a61447',
    messagingSenderId: '235265179206',
    projectId: 'seu-jobapp',
    authDomain: 'seu-jobapp.firebaseapp.com',
    storageBucket: 'seu-jobapp.appspot.com',
    measurementId: 'G-LNH9ZBYVXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStj6ces0UdQfz6P7dhaQ1WQGAIpeL8Pg',
    appId: '1:235265179206:android:f6b796522b59a78ba61447',
    messagingSenderId: '235265179206',
    projectId: 'seu-jobapp',
    storageBucket: 'seu-jobapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrBsBDTGYvROM0f7AMT5fuKCXSzlJDbVY',
    appId: '1:235265179206:ios:a0b4ef661c3a433ba61447',
    messagingSenderId: '235265179206',
    projectId: 'seu-jobapp',
    storageBucket: 'seu-jobapp.appspot.com',
    iosBundleId: 'com.example.seujobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrBsBDTGYvROM0f7AMT5fuKCXSzlJDbVY',
    appId: '1:235265179206:ios:a0b4ef661c3a433ba61447',
    messagingSenderId: '235265179206',
    projectId: 'seu-jobapp',
    storageBucket: 'seu-jobapp.appspot.com',
    iosBundleId: 'com.example.seujobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg8afJNgbJqDmnQTtuzZV7-pdKjePgCQg',
    appId: '1:235265179206:web:af028014d297d95ea61447',
    messagingSenderId: '235265179206',
    projectId: 'seu-jobapp',
    authDomain: 'seu-jobapp.firebaseapp.com',
    storageBucket: 'seu-jobapp.appspot.com',
    measurementId: 'G-B6FP0GGJDJ',
  );

}